name: ttraining_record
description: "A new Flutter project."
publish_to: 'none'

# Flutter Intl（多言語化）
flutter_intl:
  enabled: true
  main_locale: kl

# バージョン
version: 1.1.10+22

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # UI / グラフ
  fl_chart: ^0.68.0
  # 広告
  google_mobile_ads: ^6.0.0
  # UI コンポーネント
  numberpicker: ^2.1.2
  cupertino_icons: ^1.0.8
  table_calendar: ^3.1.2
  # データ/永続化
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # i18n
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  # パッケージ名変更ツール
  change_app_package_name: ^1.5.0
  # その他
  collection: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  # コード生成とリンティング
  flutter_lints: ^6.0.0
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  # ランチャーアイコン生成
  flutter_launcher_icons: ^0.14.4

# ---- ランチャーアイコン設定 ----
flutter_launcher_icons:
  android: true
  ios: true

  # iOS 用（背景白 1024px アイコン）
  image_path: assets/app_icons/icon_ios_1024.png
  remove_alpha_ios: true   # 透過は不可なので白で塗りつぶし

  # Android 用（余白ゼロ、背景グレー #B3B8BC）
  adaptive_icon_foreground: assets/app_icons/icon_foreground.png
  adaptive_icon_background: assets/app_icons/icon_background.png
  adaptive_icon_monochrome: assets/app_icons/icon_monochrome.png


# Flutter 本体設定
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/backgrounds/
    - assets/app_icons/
