// lib/constants/backgrounds.dart
const List<String> allBackgrounds = [
  'assets/backgrounds/bg01.png',
  'assets/backgrounds/bg02.png',
  'assets/backgrounds/bg03.png',
  'assets/backgrounds/bg04.png',
  'assets/backgrounds/bg05.png',
  'assets/backgrounds/bg06.png',
  'assets/backgrounds/bg07.png',
  'assets/backgrounds/bg08.png',
  'assets/backgrounds/bg09.png',
  'assets/backgrounds/bg10.png',
  'assets/backgrounds/bg11.png',
  'assets/backgrounds/bg12.png',
  'assets/backgrounds/bg13.png',
  'assets/backgrounds/bg14.png',
  'assets/backgrounds/bg15.png',
  'assets/backgrounds/bg16.png',
  'assets/backgrounds/bg17.png',
  'assets/backgrounds/bg18.png',
  'assets/backgrounds/bg19.png',
  'assets/backgrounds/bg20.png',
];
